# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: xenial
sudo: false
warnings_are_errors: false

r_packages:
    - covr

r_github_packages:
    - rstudio/keras

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - name: "tf-1.15"
      env:
        - TENSORFLOW_VERSION="1.15.0"
        - TFPROBABILITY_VERSION="0.8"
    - name: "tf-2.0"
      env:
        - TENSORFLOW_VERSION="2.0"
        - TFPROBABILITY_VERSION="0.8"
    - name: "tf-nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TFPROBABILITY_VERSION="nightly"
  allow_failures:
    - name: "tf-nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TFPROBABILITY_VERSION="nightly"

before_script:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
  - pip3 install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - Rscript -e 'tfprobability::install_tfprobability(version = Sys.getenv("TFPROBABILITY_VERSION"), tensorflow = Sys.getenv("TENSORFLOW_VERSION"), extra_packages = "gast==0.2.2")'
  - Rscript -e 'tensorflow::tf_config()'
  - Rscript -e 'tfprobability::tfp_version()'

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - sigrid@rstudio.com
    on_success: never
    on_failure: always
