# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

warnings_are_errors: false

r_packages:
    - covr

r_github_packages:
    - rstudio/keras
    - rstudio/tensorflow

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - name: "tf-2.1"
      env:
        - TENSORFLOW_VERSION="2.1"
        - TFPROBABILITY_VERSION="0.9"
    - name: "tf-2.0"
      env:
        - TENSORFLOW_VERSION="2.0"
        - TFPROBABILITY_VERSION="0.8"
    - name: "tf-nightly"
      env:
        - TENSORFLOW_VERSION="nightly-cpu"
        - TFPROBABILITY_VERSION="nightly"
  allow_failures:
    - name: "tf-nightly"
      env:
        - TENSORFLOW_VERSION="nightly-cpu"
        - TFPROBABILITY_VERSION="nightly"

addons:
  apt:
    packages:
      python3-dev
      python3-pip
      python3-virtualenv
      python3-venv
      python3-setuptools

before_script:
  - python3 -m pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - Rscript -e 'Sys.setenv(PIP_QUIET=1); tfprobability::install_tfprobability(version = Sys.getenv("TFPROBABILITY_VERSION"), tensorflow = Sys.getenv("TENSORFLOW_VERSION"), extra_packages = "gast==0.2.2")'
  - Rscript -e 'tensorflow::tf_config()'
  - Rscript -e 'tfprobability::tfp_version()'

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - sigrid@rstudio.com
    on_success: never
    on_failure: always
