# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

environment:
  NOT_CRAN: true
  USE_RTOOLS: true
  matrix:
    - TF_VERSION: 1.15.0
      TFP_VERSION: 0.8
    - TF_VERSION: 2.0
      TFP_VERSION: 0.8
    - TF_VERSION: nightly
      TFP_VERSION: nightly


# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps
  - R CMD INSTALL .
  - R -e "tfprobability::install_tfprobability(version = Sys.getenv('TFP_VERSION'), tensorflow = Sys.getenv('TF_VERSION'), method = 'conda')"

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
